print("="*50)
print("203local Data Engine")
print("="*50)
print("1. Dashboard")
print("2. Load + Backup Master")
print("3. Validate Master Spreadsheet")
print("4. Export Website CSV")
print("5. Exit")
